# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WWW_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
